// <auto-generated />
using System;
using System.Collections.Generic;
using EfCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106213810_adds softdeletion and tenantid queryfilters")]
    partial class addssoftdeletionandtenantidqueryfilters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-rc.2.25502.107")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfCore.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShippingInfo", "EfCore.Models.Order.ShippingInfo#ShippingInfo", b1 =>
                        {
                            b1.Property<string>("Carrier");

                            b1.Property<DateTime?>("EstimatedDelivery");

                            b1.Property<DateTime?>("ShippedDate");

                            b1.Property<string>("TrackingNumber");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "ShippingAddress", "EfCore.Models.Order.ShippingInfo#ShippingInfo.ShippingAddress#Address", b2 =>
                                {
                                    b2.Property<string>("City")
                                        .IsRequired();

                                    b2.Property<string>("Country");

                                    b2.Property<string>("PostalCode")
                                        .IsRequired();

                                    b2.Property<string>("State")
                                        .IsRequired();

                                    b2.Property<string>("Street")
                                        .IsRequired();
                                });

                            b1.ToJson("ShippingInfoJson");
                        });

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("EfCore.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("EfCore.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Address", "EfCore.Models.Person.Address#Address", b1 =>
                        {
                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_City");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Country");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_PostalCode");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_State");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("Address_Street");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ContactInfo", "EfCore.Models.Person.ContactInfo#ContactInfo", b1 =>
                        {
                            b1.Property<string>("Email");

                            b1.Property<string>("PhoneNumber");

                            b1.PrimitiveCollection<string>("SocialMediaHandles")
                                .IsRequired();

                            b1.Property<string>("Website");

                            b1.ToJson("ContactInfoJson");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Stats", "EfCore.Models.Person.Stats#PersonStats", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTime>("LastOrderDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("Stats_LastOrderDate");

                            b1.Property<int>("TotalOrders")
                                .HasColumnType("int")
                                .HasColumnName("Stats_TotalOrders");

                            b1.Property<decimal>("TotalSpent")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Stats_TotalSpent");
                        });

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EfCore.Models.Order", b =>
                {
                    b.HasOne("EfCore.Models.Person", "Person")
                        .WithMany("Orders")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("EfCore.Models.OrderItem", b =>
                {
                    b.HasOne("EfCore.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("EfCore.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("EfCore.Models.Person", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
